export { default as _advantages } from './_advantages';
export { default as _clients } from './_clients';
export { default as _fastCommunication } from './_fastCommunication';
export { default as _gratefulCompanies } from './_gratefulCompanies';
export { default as _partners } from './_partners';
export { default as _shareProject } from './_shareProject';
export { default as _contactData } from './_contactData';
export { default as _faqData } from './_faqData';
export { default as _privacyPolicyData } from './_privacyPolicyData';
