export * from './animate';
export * from './label';
export * from './carousel';
export * from './cards';
export * from './custom-breadcrumbs';
export * from './lightbox';
export * from './SideCards';
// export * from './feedBackForms';
export * from './iconify/Iconify';

export { default as Page } from './Page';
export { default as SplitMarker } from './SplitMarker';
export { default as Logo } from './Logo';
export { default as Viber } from './Viber';
export { default as Vk } from './Vk';
export { default as Copy } from './Copy';
export { default as SocialNetworksButton } from './SocialNetworksButton';
export { default as Image } from './Image';
export { default as TextMaxLine } from './TextMaxLine';
export { default as Scrollbar } from './Scrollbar';
export { default as NavSection } from './NavSection';
export { default as TextIconLabel } from './TextIconLabel';
export { default as BgOverlay } from './BgOverlay';
export { default as Typewriter } from './TypeWriter';
export { default as ProgressBar } from './ProgressBar';
export { default as Markdown } from './Markdown';
export { default as ManagerMessengersIcons } from './ManagerMessengersIcons';
export { default as HowItWork } from './HowItWork';
export { default as DetailsGallery } from './DetailsGallery';
export { default as SearchNotFound } from './SearchNotFound';
export { default as SvgColor } from './SvgColor';
export { default as SvgIconStyle } from './SvgIconStyle';
export { default as CountUpNumber } from './CountUpNumber';
export { default as TimeSlotSelector } from './TimeSlotSelector';